name: geekbench4
version: 4.2.0
summary: Cross-Platform Benchmark
description: |
  Geekbench 4 measures your system's power and tells
  you whether your computer is ready to roar. How
  strong is your mobile device or desktop computer?
  How will it perform when push comes to crunch?
  These are the questions that Geekbench can answer.

confinement: devmode
base: core22

parts:
  geekbench4:
    plugin: dump
    source: https://cdn.geekbench.com/Geekbench-$SNAPCRAFT_PROJECT_VERSION-Linux.tar.gz

apps:
  geekbench4:
    command: geekbench4

lint:
  ignore:
    - library
